version: '3'
services: 
    # Have to run always 
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        # 3050 mapped to 80 in the container - see default.conf 
        ports: 
            - '3050:80'
    postgres: 
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis: 
        image: 'redis:latest'
    api: 
        depends_on:
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        # Volumes - to share files between a host system and the Docker container
        # Changes in the local server folders will appear in the docker file 
        volumes: 
            - ./server:/app 
        # ENV is used only at runtime 
        environment: 
            # Possible to access other services by name 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        tty: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - ./client:/app 
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - ./worker:/app 
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    
